GET  http://localhost:3000/

###------------------ items routes
GET  http://localhost:3000/items
###
GET  http://localhost:3000/items/list?page=1&limit=10
###
GET  http://localhost:3000/items/223851
###
GET http://localhost:3000/items/timeFilter?start=1995&end=2000&page=1&limit=5
###
GET http://localhost:3000/items/titleFilter?title=Garden
###
GET http://localhost:3000/items/denomFilter?start=40&end=50

###------------------ users routes
GET http://localhost:3000/users
###
GET http://localhost:3000/users/2
###
GET http://localhost:3000/users/3/lists


###------------------ collection routes
GET http://localhost:3000/users/1/collection
### chỗ này hơi cấn ???
GET http://localhost:3000/users/2/collection/5

###
GET http://localhost:3000/users/1/collection/list
###
GET http://localhost:3000/users/1/collection/favourite
###
GET http://localhost:3000/users/2/collection/all


###------------------ authentication routes
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "userName": "user1",
    "password": "password1"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userName": "user7",
    "password": "password6",
    "email":  "user6@gmail.com"
}
###
GET http://localhost:3000/auth/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkpvaG4iLCJpYXQiOjE3MzE1ODM5NzUsImV4cCI6MTczMTU4Mzk5NX0.PssrQxw1r5dA4j_SUw7dAyw7iqcNThPHiQdL88QSLi8
###
POST http://localhost:3000/auth/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkpvaG4iLCJwYXNzd29yZCI6MTIzLCJpYXQiOjE3MzE1ODM5Mzd9.47VqCAjD_J4VmATA3eZAOhfZ5KQKctqgsQEHsI361a4"
}

###
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkpvaG4iLCJwYXNzd29yZCI6MTIzLCJpYXQiOjE3MzE1ODM5Mzd9.47VqCAjD_J4VmATA3eZAOhfZ5KQKctqgsQEHsI361a4"
}


